### ISSUE TITLE
[Bazel CI] ERROR: Analysis of target '@@rules_go+//:cgo_context_data' failed

### ISSUE THREAD

**Issue by satyanandak** [bazelbuild/buildtools#1415]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/5070#019a711a-b230-4505-887c-b80afc72eae1

Platform: Ubuntu, MacOS

Logs:
```
(04:10:23) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/34a43d17c154cc42262035357bb19c95/external/rules_go+/BUILD.bazel:88:17: Analysis of target '@@rules_go+//:cgo_context_data' (config: 87b2e4d) failed
(04:10:24) ERROR: Analysis of target '//warn/docs:docs_test' failed; build aborted: Analysis failed
(04:10:24) INFO: Elapsed time: 5.251s, Critical Path: 0.04s
(04:10:24) INFO: 1 process: 1 internal.
(04:10:24) ERROR: Build did NOT complete successfully
(04:10:24) ERROR: No test targets were found, yet testing was requested
(04:10:24) FAILED:
```
Steps:
```
git clone https://github.com/bazelbuild/buildtools
git reset 9a9819efe30f571dda70302ebe7acca5d4f63bdf --hard
export USE_BAZEL_VERSION=c32926f879b4378c7df8e54c93b00f1a7feef901
bazel test //...
```
CC Greenteam @kotlaja

**Comment by oreflow** [comment]
I assume this was resolved as it looks severe and has been stale for 2 months. Please reopen otherwise and I'll take a look at it

**Comment by kotlaja** [comment]
Please reopen this issue since it's still not fixed - The same error is visible at [the latest Bazel@HEAD run](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/5196#019ba0f2-549f-4f31-a122-923de5883865). 

> it looks severe

I don't think this is severe since it is Bazel@HEAD, not a stable released version of Bazel. I will take a look these days (I've been on a vacation for a month :) + I've been fixing multiple other BazelCI errors these days). Unless you're eager to fix it yourself - Please go for it :))

**Comment by kotlaja** [comment]
Fixed in https://github.com/bazelbuild/buildtools/pull/1438, please take a look. 

> Please reopen this issue since it's still not fixed

I got permissions now, I'll open it.

**Comment by oreflow** [comment]
Thanks for fixing this
